// Language resources for the public tracker.  Data IDs, URLs, dates and status
// keys deliberately remain in trackerData.js; this module only supplies display copy.
export const DEFAULT_LANGUAGE = "en";
export const SUPPORTED_LANGUAGES = ["en", "ms"];

const EN = {
  metadata: { title: "PCDS 2030 Dashboard: Projects & Status | Sarawak", description: "Explore the PCDS 2030 dashboard for the Sarawak Post COVID-19 Development Strategy 2030, with project status, milestones, and public sources." },
  languageControl: { label: "Language", current: "English", switchTo: "Bahasa Melayu" },
  navigation: { tracker: "Project tracker", updates: "PCDS 2030 updates" },
  updatesPage: {
    title: "Updates",
    intro: "A dated record of meaningful public developments reflected in the project tracker, with a supporting source for each entry.",
    entriesLabel: "PCDS 2030 public developments",
    backToTracker: "Project tracker",
    source: "Source:",
  },
  themeToggle: { label: "Theme", light: "Light", dark: "Dark", system: "System" },
  status: {
    "Awaiting Decision": { label: "Ongoing", description: "delivery moving, pending approval, or awaiting next public decision" },
    "In Progress": { label: "Ongoing", description: "delivery moving, pending approval, or awaiting next public decision" },
    Planning: { label: "Planning", description: "scope or delivery being shaped" },
    Operational: { label: "Completed", description: "in use or completed" },
    Designated: { label: "Completed", description: "outcome formally achieved" },
    Enacted: { label: "Completed", description: "law or policy in effect" },
    fallback: { label: "Status", description: "Status is based on available public reporting." },
  },
  filters: { all: "All", planning: "Planning", ongoing: "Ongoing", completed: "Completed" },
  metrics: { trackedProjects: "Projects", planning: "Planning", ongoing: "Ongoing", completed: "Completed", milestones: "Milestones" },
  milestones: { label: "Milestones", remaining: "Remaining Milestones", next: "Next Milestone", completed: "Completed", noOpen: "No open milestone", none: "No milestones", count: (done, total) => `${done}/${total} milestones`, progress: (done, total) => `${done} of ${total} milestones completed` },
  facts: { lead: "Lead / parties", value: "Reported value", sources: "Sources" },
  card: { sector: "Sector", enabler: "Enabler", viewDetails: "View details +", hideDetails: "Hide details −", expand: (name) => `View details for ${name}`, collapse: (name) => `Hide details for ${name}` },
  header: {
    kicker: "Sarawak Development Monitor", title: "Project Tracker", lastUpdated: "Last updated:",
    intro: ["PCDS 2030 is the Sarawak Government's 10-year Post COVID-19 Development Strategy for sustainable, high-income growth driven by data and innovation. It targets 8% annual growth, from RM136 billion in 2019 to RM282 billion by 2030.", "This project tracker brings major projects, their current status, key milestones, and links to publicly available sources into one scan-first view."],
  },
  footer: { independent: "Built by hafiy.my — an independent tracker. Not affiliated with the Sarawak Government.", methodology: "Data sourced from public reports, news outlets, and official announcements. Milestone statuses are best-effort based on available information." },
  accessibility: { environment: (name) => `${name} environment` },
};

const MS = {
  metadata: { title: "Papan Pemuka PCDS 2030: Projek & Status | Sarawak", description: "Terokai papan pemuka PCDS 2030 bagi Strategi Pembangunan Pasca COVID-19 Sarawak 2030, termasuk status projek, pencapaian dan sumber awam." },
  languageControl: { label: "Bahasa", current: "Bahasa Melayu", switchTo: "English" },
  navigation: { tracker: "Project tracker", updates: "Kemas kini PCDS 2030" },
  updatesPage: {
    title: "Kemas Kini",
    intro: "Rekod bertarikh mengenai perkembangan awam penting yang dicerminkan dalam 'project tracker', berserta sumber sokongan bagi setiap catatan.",
    entriesLabel: "Perkembangan awam PCDS 2030",
    backToTracker: "Project tracker",
    source: "Sumber:",
  },
  themeToggle: { label: "Tema", light: "Cerah", dark: "Gelap", system: "Sistem" },
  status: {
    "Awaiting Decision": { label: "Pelaksanaan", description: "pelaksanaan bergerak, menunggu kelulusan atau keputusan awam seterusnya" },
    "In Progress": { label: "Pelaksanaan", description: "pelaksanaan bergerak, menunggu kelulusan atau keputusan awam seterusnya" },
    Planning: { label: "Perancangan", description: "skop atau pelaksanaan sedang dirangka" },
    Operational: { label: "Selesai", description: "telah digunakan atau diselesaikan" },
    Designated: { label: "Selesai", description: "hasil telah diiktiraf secara rasmi" },
    Enacted: { label: "Selesai", description: "undang-undang atau dasar telah berkuat kuasa" },
    fallback: { label: "Status", description: "Status adalah berdasarkan laporan awam yang tersedia." },
  },
  filters: { all: "Semua", planning: "Perancangan", ongoing: "Pelaksanaan", completed: "Selesai" },
  metrics: { trackedProjects: "Projek", planning: "Perancangan", ongoing: "Pelaksanaan", completed: "Selesai", milestones: "Pencapaian" },
  milestones: { label: "Pencapaian Utama", remaining: "Pencapaian Utama yang Baki", next: "Pencapaian Seterusnya", completed: "Selesai", noOpen: "Tiada pencapaian utama yang belum selesai", none: "Tiada pencapaian utama", count: (done, total) => `${done}/${total} pencapaian`, progress: (done, total) => `${done} daripada ${total} pencapaian utama selesai` },
  facts: { lead: "Peneraju / pihak terlibat", value: "Nilai dilaporkan", sources: "Sumber" },
  card: { sector: "Sektor", enabler: "Pemboleh", viewDetails: "Lihat butiran +", hideDetails: "Sembunyikan butiran −", expand: (name) => `Lihat butiran ${name}`, collapse: (name) => `Sembunyikan butiran ${name}` },
  header: {
    kicker: "Sarawak Development Monitor", title: "Project Tracker", lastUpdated: "Kemas kini terakhir:",
    intro: ["PCDS 2030 ialah Strategi Pembangunan Pasca COVID-19 Kerajaan Sarawak selama 10 tahun untuk pertumbuhan mampan berpendapatan tinggi yang dipacu data dan inovasi. Strategi ini menyasarkan pertumbuhan tahunan 8%, daripada RM136 bilion pada 2019 kepada RM282 bilion menjelang 2030.", "'Project tracker' ini menghimpunkan projek, status pelaksanaan, pencapaian dan pautan kepada sumber awam dalam satu paparan yang mudah diteliti."],
  },
  footer: { independent: "'Project tracker' dibangunkan oleh — hafiy.my. Tidak berafiliasi dengan Kerajaan Sarawak.", methodology: "Data diperoleh daripada laporan awam, portal berita dan pengumuman rasmi. Status pencapaian utama ialah rumusan terbaik berdasarkan maklumat yang tersedia." },
  accessibility: { environment: (name) => `persekitaran ${{ development: "pembangunan", preview: "pratonton", production: "produksi" }[name] || name}` },
};

/** Returns all fixed rendered copy. Unknown languages safely use English. */
export function getUiCopy(language = DEFAULT_LANGUAGE) {
  return language === "ms" ? MS : EN;
}

const SECTOR_NAMES = {
  manufacturing: "Pembuatan", agriculture: "Pertanian Komersial", tourism: "Pelancongan", forestry: "Perhutanan", mining: "Perlombongan", "social-services": "Perkhidmatan Sosial", "digital-transformation": "Transformasi Digital", innovation: "Inovasi", education: "Pendidikan dan Modal Insan", infrastructure: "Infrastruktur Asas", utilities: "Utiliti", transport: "Pengangkutan", "renewable-energy": "Tenaga Boleh Baharu", overview: "Kerangka PCDS 2030",
};

// Explicit editorial translations keyed by immutable canonical project name. Source labels
// remain source-language citations so that linked report/article titles are not misrepresented.
const PROJECT_TRANSLATIONS = {
  "SMD Semiconductor — GaN Chip Development": { displayName: "Pembangunan Cip Gallium Nitride (GaN)", lead: "SMD Semiconductor (milik kerajaan negeri)", value: "Tidak didedahkan", summary: "Usaha niaga semikonduktor milik kerajaan negeri Sarawak yang membangunkan cip semikonduktor sebatian berasaskan Gallium Nitride (GaN), dipertingkatkan dengan AI. Platform keteq.GaN dan keteq.ai telah diperkenalkan kepada umum; pendaftaran harta intelek global dan pengkomersialan masih menjadi bukti kemajuan seterusnya yang dapat dilihat.", milestones: ["Premier mengumumkan kejayaan pembangunan cip GaN", "Pendaftaran harta intelek global", "Pengkomersialan bermula"] },
  "RM1 Billion Paddy Infrastructure Programme": { displayName: "Program Infrastruktur Padi", lead: "Kerajaan Sarawak / Jabatan Pertanian", value: "RM1 bilion", summary: "Program pengairan, perparitan dan jalan ladang padi di seluruh negeri untuk meningkatkan sara diri beras. RM1 bilion telah diperuntukkan, dengan kawal selia pelaksanaan bagi memastikan infrastruktur kekal khusus untuk padi dan menyokong sasaran pengeluaran beras Sarawak sebanyak 500,000 tan pada 2030.", milestones: ["Peruntukan RM1 bilion bagi penanaman padi diumumkan", "Pengelompokan petani dan pajakan tanah padi", "Pengeluaran beras tahunan mencapai 500,000 tan"] },
  "Sarawak Agrotechnology Park": { displayName: "Taman Agroteknologi Sarawak", lead: "Kerajaan Sarawak", value: "RM19.5 juta", summary: "Tapak Taman Agro-Teknologi Sarawak di Semenggok dan Tarat bertujuan menarik syarikat pertanian berasaskan teknologi. Laporan rasmi M-FICORD menyatakan ladang udang kara di SARTECH Tarat telah beroperasi sejak 2022, manakala Belanjawan Sarawak 2026 memperuntukkan RM19.5 juta bagi pembangunan lanjut kedua-dua tapak. Penyiapan pembangunan tapak yang lebih luas masih belum disahkan kepada umum.", milestones: ["Ladang udang kara mula beroperasi di SARTECH Tarat", "RM5 juta diperuntukkan kepada Semenggok dan Tarat", "Peruntukan pembangunan RM19.5 juta diumumkan", "Pembangunan tapak Semenggok dan Tarat mencapai penyiapan"] },
  "Sungai Baji Agropark": { displayName: "Agropark Sungai Baji", lead: "Kementerian Industri Makanan, Komoditi dan Pembangunan Wilayah / LCDA", value: "Tidak didedahkan", summary: "Pembangunan pertanian komersial di Sungai Baji, Sarikei. Laporan rasmi menyatakan komponen infrastruktur dan pertanian siap pada Oktober 2025, manakala LCDA melantik syarikat peneraju pada Mei 2025. Operasi dan pengeluaran komersial kekal sebagai pencapaian awam seterusnya.", milestones: ["LCDA melantik syarikat peneraju", "Komponen infrastruktur dan pertanian siap", "Operasi agropark bermula", "Pengeluaran komersial bermula"] },
  "Sarawak Delta Geopark - UNESCO Global Geopark Designation": { displayName: "Geopark Global UNESCO Delta Sarawak", lead: "Kerajaan Sarawak / UNESCO", value: "Tidak didedahkan", summary: "Geopark seluas 3,112 km² meliputi wilayah Kuching-Santubong-Bako. Diiktiraf secara rasmi sebagai Geopark Global UNESCO pada 27 April 2026 — yang ketiga di Malaysia selepas Langkawi dan Kinabalu. Dijenamakan \"Borneo's Cradle of Origin\" kerana warisan geologinya yang unik.", milestones: ["Dossier pencalonan geopark disediakan", "Penilaian lapangan UNESCO selesai", "Penerimaan Majlis UNESCO diperoleh", "Diiktiraf sebagai Geopark Global UNESCO"] },
  "The Archaeological Heritage of Niah National Park’s Caves Complex": { displayName: "Tapak Warisan Arkeologi Gua Niah", lead: "Sarawak Forestry Corporation / Jabatan Muzium Sarawak", value: "Tidak didedahkan", summary: "Kompleks Gua Niah dalam Taman Negara Niah memelihara sekurang-kurangnya 50,000 tahun interaksi manusia dengan persekitaran hutan hujan. UNESCO menyenaraikan tapak ini sebagai Tapak Warisan Dunia pada 2024 di bawah nama rasmi The Archaeological Heritage of Niah National Park’s Caves Complex.", milestones: ["Dicalonkan untuk penyenaraian Warisan Dunia UNESCO", "Disenaraikan sebagai Tapak Warisan Dunia UNESCO"] },
  "Environment (Reduction of Greenhouse Gases Emission) Ordinance 2023": { displayName: "Ordinan Pelepasan Gas Rumah Hijau 2023", lead: "Kerajaan Sarawak", value: "Tidak berkenaan", summary: "Menyediakan kerangka negeri untuk mengawal selia dan mengurus pelepasan gas rumah hijau. Sistem Pengurusan Gas Rumah Hijau Fasa 1 NREB mula beroperasi pada Februari 2026. Sektor ekonomi berjadual mesti mendaftar dan mengemukakan laporan tahunan pelepasan karbon yang disokong oleh juruaudit luar bertauliah.", milestones: ["Ordinan dikuatkuasakan", "Peraturan juruaudit luar bertauliah diwujudkan", "GHG-MS Fasa 1 mula beroperasi", "Sektor berjadual mengemukakan laporan pelepasan yang disahkan"] },
  "Semenggoh Rainforest Discovery Centre": { displayName: "Pusat Penemuan Hutan Hujan Semenggoh", lead: "Kementerian Pembangunan Bandar dan Sumber Asli / Sarawak Forestry Corporation", value: "RM30 juta", summary: "Pembangunan ekopelancongan dan penyelidikan biodiversiti tiga peringkat dalam Rizab Semula Jadi Semenggoh. Projek ini menggabungkan naik taraf pintu masuk pusat hidupan liar, kemudahan pelawat, taman botani dan infrastruktur penyelidikan. RM30 juta serta majlis peletakan batu asas dilaporkan pada Ogos 2020.", milestones: ["Majlis asas dan peruntukan RM30 juta diumumkan", "Zon Pusat Hidupan Liar Fasa 1 mencapai penyiapan", "Zon Pintu Masuk Fasa 2 mencapai penyiapan", "Zon Botani Fasa 3 mencapai penyiapan"] },
  "Piasau Nature Reserve Discovery Centre": { displayName: "Pusat Penemuan Rizab Alam Piasau", lead: "Sarawak Forestry Corporation / Kerajaan Sarawak", value: "RM30 juta", summary: "Kemudahan ekopelancongan marin dan pemuliharaan di Rizab Alam Piasau di Miri. Pembangunan ini akan menambah pusat interpretasi dan pejabat bagi menyokong pengurusan Taman Negara Terumbu Karang Miri-Sibuti dan Taman Negara Beting Luconia. Pembinaan bermula pada Ogos 2025 dan dijadualkan siap pada awal Ogos 2027.", milestones: ["Pembangunan pusat penemuan bermula", "Pusat penemuan mencapai penyiapan"] },
  "Bau Gold Project": { displayName: "Projek Emas Bau", lead: "Besra Gold Inc / North Borneo Gold Sdn Bhd", value: "RM1.38 bilion", summary: "Projek penerokaan dan pembangunan emas di Bau yang diterajui Besra Gold melalui North Borneo Gold. Laporan PCDS 2030 Highlights 2023 mengunjurkan RM1.38 bilion pelaburan huluan. Semakan bebas pada November 2025 mengenal pasti tempoh pegangan dan kajian teknikal lanjut sebagai kritikal, manakala pengumuman 2026 merekodkan kemajuan bersyarat bagi pembaharuan pajakan perlombongan Jugan. Jadual pembangunan komersial masih belum disahkan.", milestones: ["Semakan teknikal bebas selesai", "Pembaharuan pajakan perlombongan Jugan diluluskan secara bersyarat", "Syarat pembaharuan pajakan bersyarat diterima", "Pemuktamadan syarat pajakan perlombongan"] },
  "Sarawak Cancer Centre": { displayName: "Pusat Kanser Sarawak", lead: "JKR / Kerajaan Sarawak", value: "RM1.52 bilion", summary: "Pusat kanser khusus pertama Sarawak di Kota Samarahan, dengan anggaran awal projek RM1.52 bilion. Sarawak mendahulukan RM500 juta untuk peralatan perubatan, dan projek memasuki perolehan reka dan bina pada Julai 2026. Pembinaan disasarkan bermula pada Januari 2027, dengan penyiapan dijangka pada 2032.", milestones: ["Anggaran kos awal RM1.52 bilion diumumkan", "Perdana Menteri mengarahkan tender S1 2026 dipercepatkan", "Sarawak memperuntukkan RM500 juta untuk peralatan perubatan", "Peringkat perolehan reka dan bina disahkan", "Pembinaan bermula", "Pusat kanser mencapai penyiapan"] },
  "FutureData — Kuching Data Centre Park": { displayName: "Taman Pusat Data Kuching", lead: "TSG Group / Global Telecommunications Group", value: "USD130 juta", summary: "Taman pusat data 500MW di Kuching, dengan USD130 juta dilaporkan bagi Fasa 1. Kemudahan pertama mempunyai kapasiti IT 17MW untuk Global Telecommunications Group. Selaras dengan Pelan Tindakan Ekonomi Digital Sarawak 2030. Tenaga hidro Sarawak yang banyak menjadikannya menarik untuk operasi pusat data berintensif tenaga, dengan operasi pertama disasarkan pada 2026.", milestones: ["Pembinaan kemudahan pertama bermula", "Pusat data 17MW pertama mula beroperasi"] },
  "CHITOSE Carbon Capture Central Sarawak": { displayName: "CHITOSE Tangkapan Karbon Central Sarawak", lead: "CHITOSE Group / Sarawak Energy / Sarawak Biodiversity Centre", value: "Tidak didedahkan", summary: "Kemudahan penyelidikan pengeluaran mikroalga industri dan tangkapan karbon di loji janakuasa arang batu Sejingkat milik Sarawak Energy. C4 Sarawak menangkap CO2 daripada gas serombong untuk penanaman mikroalga, dengan jangkaan pengeluaran tahunan 450 tan CO2 yang ditangkap dan 300 tan biojisim kering.", milestones: ["Projek tangkapan karbon mikroalga bermula", "Kemudahan mikroalga industri dilancarkan secara rasmi"] },
  "Sarawak Bioindustrial Park": { displayName: "Taman Bioindustri Sarawak", lead: "Sarawak Biodiversity Centre / BioVerde Technologies", value: "Tidak didedahkan", summary: "Hab bioindustri dan pengkomersialan yang bertujuan menukarkan penyelidikan biodiversiti Sarawak kepada pengeluaran berasaskan bio yang boleh diskalakan. Sumber rasmi dan awam menerangkan taman seluas 100 ekar dengan lot industri, pemprosesan bio perintis, makmal analitikal dan pembuatan GMP; BioVerde menyatakan taman ini dalam pembangunan dan rakan peneraju serta penyelidikan sedang dipilih.", milestones: ["Pemilihan rakan peneraju dan penyelidikan", "Kemudahan pemprosesan bio perintis, makmal dan GMP mencapai penyiapan", "Operasi taman bermula"] },
  "Kota Petra Green Technology Park": { displayName: "Taman Teknologi Hijau Kota Petra", lead: "Zecon Berhad", value: "RM328 juta", summary: "Pembangunan teknologi hijau seluas 3,000 ekar berhampiran Taman Perindustrian Demak Laut dan Pelabuhan Senari yang menggabungkan penjanaan solar, penyimpanan bateri dan tapak pusat data sedia AI. Fasa 1 meliputi 300 ekar dan kemudahan solar agrovoltaik 100MWac. Penyediaan tapak sedang berjalan menjelang Mei 2026 dan kontrak EPCC RM328 juta dianugerahkan pada Julai 2026, dengan operasi komersial dijadualkan pada Disember 2027.", milestones: ["Lesen penjanaan solar 300MW diperoleh", "Perjanjian pembelian tenaga 30 tahun ditandatangani", "Penyediaan tapak Fasa 1 mencapai 150 ekar dibersihkan", "Kontrak EPCC Fasa 1 RM328 juta dianugerahkan", "Pembersihan tapak Fasa 1 selesai", "Operasi komersial bermula", "Jambatan kekal Sungai Serai mencapai penyiapan"] },
  "PETRONAS Kasawari Carbon Capture and Storage Project": { displayName: "Projek Tangkapan dan Penyimpanan Karbon Kasawari", lead: "PETRONAS / MMHE", value: "Tidak didedahkan", summary: "Projek tangkapan dan penyimpanan karbon luar pesisir yang berkaitan dengan Medan Kasawari PETRONAS. MMHE menerima kontrak EPCIC pada November 2022 bagi platform tangkapan dan infrastruktur berkaitan. PETRONAS menyatakan pada April 2026 bahawa ia meneliti sama ada suntikan CO2 pertama boleh diawalkan ke 2027.", milestones: ["MMHE dianugerahkan kontrak EPCIC CCS Kasawari", "Pelan suntikan CO2 lebih awal diumumkan", "Suntikan CO2 pertama"] },
  "Yayasan Sarawak International Secondary Schools Expansion": { displayName: "Perluasan Sekolah Antarabangsa Yayasan Sarawak", lead: "Yayasan Sarawak / Kerajaan Sarawak", value: "Tidak didedahkan", summary: "Rangkaian sekolah menengah antarabangsa yang disokong negeri untuk memperluas akses kepada pendidikan bersilibus antarabangsa bagi pelajar berpendapatan rendah dan luar bandar. Petra Jaya mula beroperasi pada 2022; laman rasmi menyenaraikan kampus Petra Jaya, Kuching Batu 12 dan Sibu, dan laporan awam menyatakan tiga lagi sekolah disasarkan siap dalam tempoh dua hingga tiga tahun.", milestones: ["Kampus Petra Jaya mula beroperasi", "Tiga kampus siap di seluruh negeri", "Tarikh pembukaan kampus Sibu diumumkan", "Baki tiga kampus mencapai penyiapan"] },
  "SCORE — Sarawak Corridor of Renewable Energy": { displayName: "Koridor Tenaga Boleh Baharu Sarawak (SCORE)", lead: "RECODA", value: "RM125 bilion", summary: "Koridor ekonomi utama yang merangkumi nod pertumbuhan Taman Perindustrian Samalaju, Tanjung Manis, Mukah, Baram dan Tunoh. SCORE melaporkan RM125 bilion pelaburan dan 53,000 pekerjaan diwujudkan. RECODA juga menyelia URDA, HDA dan NRDA untuk pembangunan luar bandar dan pedalaman.", milestones: ["Pelaburan RM125 bilion dan 53,000 pekerjaan dilaporkan", "Perluasan taman perindustrian dan sokongan pelabur", "Penyampaian infrastruktur luar bandar melalui URDA, HDA dan NRDA"] },
  "Pan Borneo Highway Sarawak Phase 1": { displayName: "Lebuh Raya Pan Borneo Sarawak Fasa 1", lead: "Kerajaan Persekutuan / JKR", value: "RM16.5 bilion", summary: "Naik taraf dua lorong sehala sepanjang 786 km dari Telok Melano ke Miri melalui 11 pakej kerja, dengan kos pembinaan dilaporkan RM16.5 bilion. Menteri Kerja Raya melaporkan kemajuan 99.98 peratus pada Oktober 2025, dengan sepuluh pakej siap dan dibuka secara berperingkat. Pakej Kerja 11 di Miri belum siap kerana paip air LAKU perlu diganti sebelum kerja jalan dapat diteruskan.", milestones: ["Pembinaan Fasa 1 bermula", "Fasa 1 mencapai 98.6 peratus siap", "Sepuluh pakej kerja siap dan dibuka", "Pakej Kerja 11 mencapai penyiapan"] },
  "Sarawak-Sabah Link Road": { displayName: "Jalan Penghubung Sarawak-Sabah", lead: "Kerajaan Persekutuan / JKR", value: "RM7.6 bilion", summary: "Jalan pedalaman yang menghubungkan utara Sarawak dan Sabah tanpa melalui Brunei. Fasa 1 dari Lawas ke Long Luping mencapai kemajuan fizikal 70.05 peratus pada April 2026 dan dijangka siap pada 2027. Fasa 2 yang bernilai RM7.6 bilion dilancarkan pada September 2025, mencapai kemajuan 10.55 peratus pada April 2026, dan dijadualkan siap pada 2029.", milestones: ["Pembinaan Fasa 1 bermula", "Fasa 2 dilancarkan secara rasmi", "Fasa 1 mencapai kemajuan 70.05 peratus", "Fasa 1 mencapai penyiapan", "Fasa 2 mencapai penyiapan"] },
  "Bintulu-Samalaju Gas Pipeline": { displayName: "Saluran Paip Gas Bintulu-Samalaju", lead: "PETROS / Kerajaan Sarawak", value: "RM1 bilion", summary: "Saluran paip gas kira-kira 70 km yang disokong komitmen RM1 bilion untuk membekalkan Taman Perindustrian Samalaju dan stesen janakuasa kitaran gabungan Bintulu. Bahagian luar pesisir dilaporkan siap pada Oktober 2025, dan Bintulu Port Authority menerbitkan notis aktiviti prapentauliahan saluran paip pada Mei 2026. Operasi komersial secara berperingkat kini dijangka bermula pada 2027.", milestones: ["Komitmen RM1 bilion dan pembuatan paip dilaporkan", "Bahagian saluran paip luar pesisir siap", "Aktiviti prapentauliahan saluran paip dimaklumkan", "Operasi komersial secara berperingkat bermula"] },
  "Sejingkat Battery Energy Storage System": { displayName: "Sistem Penyimpanan Tenaga Bateri Sejingkat", lead: "Sarawak Energy", value: "Tidak didedahkan", summary: "Sistem penyimpanan tenaga bateri berskala utiliti pertama Malaysia, terletak di Loji Janakuasa Sejingkat di Kuching. Kemudahan 60MW/82MWh dibekalkan tenaga pada Disember 2024 dan menyediakan rizab berputar, kawal selia voltan serta frekuensi, dan pengurusan permintaan puncak bagi grid elektrik Sarawak.", milestones: ["Sistem 60MW/82MWh dibekalkan tenaga", "Pentauliahan BESS berskala utiliti diumumkan"] },
  "Sarawak-Singapore Electricity Interconnection": { displayName: "Sambungan Elektrik Sarawak-Singapura", lead: "Sarawak Energy / Sembcorp Utilities", value: "Tidak didedahkan", summary: "Sambungan rentas sempadan yang dicadangkan untuk mengeksport sekitar 1GW elektrik boleh baharu dari Sarawak ke Singapura. Energy Market Authority Singapura memberi kelulusan bersyarat pada Oktober 2025, membolehkan projek bergerak ke arah kelulusan dan lesen kawal selia lanjut, dengan aliran elektrik dijangka sekitar 2035 atau lebih awal.", milestones: ["Kajian tekno-komersial dijalankan bersama rakan Singapura", "Kelulusan bersyarat diperoleh", "Projek memperoleh kelulusan dan lesen kawal selia lanjut", "Eksport elektrik bermula"] },
  "Miri Port Kuala Baram Capital Dredging": { displayName: "Pengorekan Modal Kuala Baram", lead: "Miri Port Authority / Rimbun Prima-CCCC JV", value: "RM238 juta", summary: "Projek pengorekan dan benteng latihan Delta Kuala Baram untuk mendalamkan serta menstabilkan saluran akses ke Pelabuhan Miri. Kontrak RM238 juta dianugerahkan kepada usaha sama Rimbun Prima-CCCC pada Jun 2024. Kemajuan fizikal mencapai kira-kira 55 peratus pada April 2026, dengan penyiapan disasarkan pada Oktober 2026.", milestones: ["Kontrak pengorekan RM238 juta dianugerahkan", "Kemajuan fizikal mencapai kira-kira 55 peratus", "Pengorekan mencapai penyiapan"] },
  "Sarawak River Aids to Navigation and Surveillance System": { displayName: "Sistem Navigasi dan Pengawasan Sungai Sarawak", lead: "Sarawak Rivers Board / Kementerian Pengangkutan Sarawak", value: "Tidak didedahkan", summary: "Kad ini kini menjejaki sistem keselamatan navigasi Sungai Sarawak yang beroperasi bersama sistem Sungai Miri berkaitan yang sedang dibina. Menteri Pengangkutan melaporkan pada Disember 2025 bahawa VTMS Sungai Sarawak beroperasi sepenuhnya dan sistem Sungai Miri disasarkan siap pada S3 2027.", milestones: ["Pemasangan fasa pertama bermula", "VTMS Sungai Sarawak beroperasi sepenuhnya", "Sistem Sungai Miri mencapai penyiapan"] },
  "KUTS — Kuching Urban Transportation System": { displayName: "Sistem Pengangkutan Bandar Kuching (KUTS)", lead: "Sarawak Metro Sdn Bhd", value: "Tidak didedahkan", summary: "Sistem Autonomous Rapid Transit (ART) berkuasa hidrogen pertama di Asia Tenggara yang diterangkan kepada umum sebagai program berfasa bernilai berbilion ringgit tanpa jumlah tepat. Fasa 1 merangkumi Laluan Biru, Merah dan Hijau serta mencapai kemajuan fizikal 38.2 peratus pada 30 April 2026. Operasi rintis dijadualkan pada S4 2026 sebelum operasi komersial penuh pada 2027.", milestones: ["Kontrak pemindahan loji hidrogen RM58 juta dianugerahkan", "Dua unit ART pertama tiba di Kuching", "Spektrum frekuensi khas untuk operasi ART diperoleh", "Fasa 1 mencapai kemajuan 38.2 peratus", "Perkhidmatan rintis ART bermula", "Pemindahan loji hidrogen Rembus siap", "Perkhidmatan komersial ART bermula", "KUTS mencapai penyiapan keseluruhan projek", "Rangkaian bas pengantara berkuasa hidrogen mula beroperasi"] },
  "Bintulu Port — State Control Handover": { displayName: "Penyerahan Pelabuhan Bintulu kepada Sarawak", lead: "Kerajaan Sarawak / Kerajaan Persekutuan", value: "RM1.8 bilion", summary: "Pengembalian Pelabuhan Bintulu kepada kawalan negeri Sarawak daripada kerajaan persekutuan di bawah penurunan kuasa MA63. Pengambilalihan bernilai RM1.8 bilion dipersetujui pada prinsipnya pada Februari 2026, dengan Perjanjian Tiga Pihak dan Perjanjian Penyempurnaan ditandatangani pada 21 Jun 2026. Pelabuhan ini akan menjadi pelabuhan utama Sarawak bagi eksport LNG dan koridor SCORE.", milestones: ["Perjanjian lanjutan 12 bulan untuk peralihan ditandatangani", "Pengambilalihan RM1.8 bilion dipersetujui pada prinsipnya", "Penilaian RM1.8 bilion disahkan selepas rundingan terperinci", "Perjanjian Tiga Pihak dan Penyempurnaan ditandatangani", "Pelabuhan Bintulu diserahkan kepada Sarawak"] },
  "New Kuching International Airport": { displayName: "Lapangan Terbang Antarabangsa Kuching Baharu", lead: "Kerajaan Sarawak / Kementerian Pengangkutan Sarawak", value: "RM10 bilion", summary: "Cadangan lapangan terbang antarabangsa baharu di Tanjung Embang yang bertujuan menjadi hab penerbangan dan logistik serantau. Pada Ogos 2025, Premier Sarawak menyifatkan RM10 bilion sebagai anggaran kos projek. Kajian pengesahan tapak dan kebolehlaksanaan selesai menjelang Mei 2026 serta mendapati lokasi itu sesuai dari segi operasi dan teknikal. Kementerian Pengangkutan Sarawak sedang meneruskan Permohonan Pembangunan Lapangan Terbang kepada kerajaan persekutuan sebelum pengambilan tanah, penyediaan tapak, reka bentuk terperinci dan pembinaan fizikal.", milestones: ["Perunding kajian kebolehlaksanaan dilantik", "Kajian pengesahan tapak dan kebolehlaksanaan selesai", "Pihak berkuasa persekutuan meluluskan Permohonan Pembangunan Lapangan Terbang", "Pembinaan fizikal lapangan terbang bermula"] },
  "Tanjung Embang Deep-Sea Port": { displayName: "Pelabuhan Laut Dalam Tanjung Embang", lead: "Kerajaan Sarawak / PETROS", value: "RM25-30 bilion", summary: "Cadangan pelabuhan laut dalam dan terminal gas dalam pembangunan bersepadu Tanjung Embang, dengan anggaran kos RM25 bilion hingga RM30 bilion. Reka bentuk pelan induk pelabuhan berada pada peringkat akhir menjelang April 2025, manakala laporan Mei 2025 mengesahkan bahawa kajian kebolehlaksanaan teknikal dan ekonomi terperinci sedang dijalankan. Laporan awam mengenal pasti Kerajaan Sarawak dan PETROS sebagai rakan pembangunan serta menjadualkan operasi bermula pada 2032, namun perolehan atau permulaan pembinaan masih belum disahkan.", milestones: ["Reka bentuk pelan induk pelabuhan mencapai peringkat akhir", "Kajian kebolehlaksanaan teknikal dan ekonomi sedang dijalankan", "Jadual operasi pelabuhan dan terminal gas diumumkan", "Operasi pelabuhan dan terminal gas bermula"] },
  "Baleh Hydroelectric Project": { displayName: "Projek Hidroelektrik Baleh", lead: "Sarawak Energy Berhad", value: "RM8 bilion", summary: "Empangan hidroelektrik 1,285MW di Sungai Baleh dalam Bahagian Kapit, diterajui Sarawak Energy. Anggaran 2017 meletakkan jumlah kos pembinaan sekitar RM8 bilion termasuk pembiayaan. Terowong lencongan siap pada September 2020, pengalihan sungai bermula pada Oktober 2020 dan kerja isian batu empangan bermula pada Mei 2025. Sarawak Energy menjadualkan penakungan takungan pada September 2027, penjanaan unit pertama pada Disember 2029 dan penjanaan penuh pada Jun 2030.", milestones: ["Terowong lencongan siap", "Pengalihan sungai bermula", "Kerja isian batu empangan bermula", "Penakungan takungan bermula", "Takungan mencapai aras operasi minimum", "Unit penjana pertama memulakan operasi", "Penjanaan kuasa penuh bermula"] },
  "Mentarang Induk Hydroelectric Project": { displayName: "Projek Hidroelektrik Mentarang Induk", lead: "PT Kayan Hydropower Nusantara / konsortium diterajui Sarawak Energy", value: "US$2.6 bilion", summary: "Projek kuasa hidro 1,375MW di Kalimantan Utara yang dibangunkan oleh PT Kayan Hydropower Nusantara, sebuah usaha sama melibatkan Sarawak Energy, Adaro Energy Indonesia dan Kayan Patria Pratama. Majlis pecah tanah diadakan pada Mac 2023 dan kerja awal dilaporkan berjalan pada tahun itu; kemajuan pembinaan fizikal semasa masih tidak jelas kepada umum.", milestones: ["Majlis pecah tanah diadakan", "Kerja awal dilaporkan berjalan", "Bekalan kuasa pertama"] },
  "Green Hydrogen Economy — H2ornbill & H2biscus": { displayName: "Projek Hidrogen H2biscus dan H2ornbill", lead: "SEDC Energy", value: "USD4.2 bilion", summary: "Dua cadangan pembangunan hidrogen hijau berskala eksport di Sarawak H2 Hub di Bintulu. Laporan pada 2024 menilai pakej perkongsian strategik lebih luas yang merangkumi H2biscus, H2ornbill, infrastruktur bersama Sarawak Hydrogen Hub serta Depot Rembus pada USD4.2 bilion. Angka ini ialah nilai pakej gabungan bersejarah, bukan pecahan mengikut projek. H2biscus memasuki reka bentuk kejuruteraan bahagian hadapan bersama rakan Korea, manakala H2ornbill diteruskan di bawah perjanjian pembangunan bersama dengan ENEOS dan Sumitomo. Kedua-dua projek mencapai peringkat reka bentuk kejuruteraan sebelum kapasiti yang dirancang dikurangkan. Konsep asal eksport H2ornbill ke Jepun digantung, dan skop kedua-dua projek memasuki penyelarasan semula berikutan ketidakpastian pembiayaan dan pembelian. Pelan projek, nilai pelaburan yang disemak semula dan garis masa pengeluaran yang dikemas kini belum diterbitkan.", milestones: ["Memorandum tenaga boleh baharu H2biscus ditandatangani", "Perjanjian pembangunan bersama H2ornbill ditandatangani", "Reka bentuk kejuruteraan bahagian hadapan H2biscus bermula", "Perjanjian pembangunan bersama H2biscus ditandatangani", "Kedua-dua projek mencapai reka bentuk kejuruteraan bahagian hadapan", "Konsep asal eksport H2ornbill ke Jepun digantung", "Skop projek eksport memasuki penyelarasan semula", "Pengumuman pelan projek dan garis masa pengeluaran yang dikemas kini", "Keputusan pelaburan muktamad untuk H2biscus dan H2ornbill", "Pembinaan kemudahan hidrogen bermula", "Pengeluaran hidrogen komersial bermula"] },
  "Batang Ai Floating Solar Farm": { displayName: "Ladang Solar Terapung Batang Ai", lead: "Sarawak Energy / China Power International Holdings / Trina Solar", value: "Tidak didedahkan", summary: "Ladang solar terapung pertama Sarawak Energy di takungan HEP Batang Ai, dibangunkan bersama China Power International Holdings dan Trina Solar. Kemudahan hibrid hidro-solar 50MW itu ditauliahkan pada Disember 2024. Sarawak Energy juga merancang peluasan tambahan 120MW di Batang Ai.", milestones: ["Pembinaan bermula secara rasmi", "Pembinaan mencapai 35 peratus siap", "Kemudahan solar terapung 50MW ditauliahkan", "Kapasiti solar terapung meningkat sebanyak 120MW"] },
  "Baram Agrovoltaic Project": { displayName: "Projek Agrovoltaik Baram", lead: "Tidak didedahkan", value: "RM6 bilion", summary: "Cadangan pembangunan agrovoltaik di Temala berhampiran Long Lama dalam Zon Ekonomi Tenaga Boleh Baharu Baram yang diluluskan negeri. Skop RM6 bilion yang dilaporkan menggabungkan 1,500 hektar pertanian moden, 500 hektar penanaman padi, hab logistik, stesen janakuasa 300MW dan bandar sokongan. Laporan rasmi projek tidak mengenal pasti pihak pelaksana, kontrak, urutan penyampaian atau jadual.", milestones: ["Skop dan anggaran projek diumumkan", "Komponen pertanian dan padi mula beroperasi", "Hab logistik mula beroperasi", "Stesen janakuasa 300MW mula beroperasi", "Bandar sokongan mencapai penyiapan"] },
  "PCDS 2030 — Overarching Framework": { displayName: "Kerangka Menyeluruh PCDS 2030", lead: "Kerajaan Sarawak", value: "RM282 bilion", summary: "Strategi Pembangunan Pasca COVID-19 2030. Visi: masyarakat makmur yang dipacu data dan inovasi. Menyasarkan pertumbuhan KDNK tahunan 8%, pendapatan isi rumah median RM15,000 menjelang 2030, pengurangan intensiti GHG 45%, dan 195,000 pekerjaan baharu. Berteraskan 6 Sektor Ekonomi dan 7 Pemboleh.", milestones: ["Melepasi ambang pendapatan tinggi Bank Dunia lebih awal daripada jadual", "Sasaran KDNK RM282 bilion", "Sasaran pendapatan isi rumah median bulanan RM15,000", "Sasaran 195,000 pekerjaan baharu"] },
};

function localizeProject(project) {
  const translation = PROJECT_TRANSLATIONS[project.name];
  if (!translation) return project;
  return {
    ...project,
    displayName: project.displayName || project.name,
    lead: translation.lead,
    value: translation.value,
    summary: translation.summary,
    milestones: project.milestones.map((milestone, index) => ({ ...milestone, text: translation.milestones[index] || milestone.text })),
  };
}

/**
 * Returns data suitable for rendering in the requested language without mutating input.
 * English returns the original reference; BM preserves every canonical name, URL, date and flag.
 */
export function localizeSectors(sectors, language = DEFAULT_LANGUAGE) {
  if (language !== "ms" || !Array.isArray(sectors)) return sectors;
  return sectors.map((sector) => ({
    ...sector,
    name: SECTOR_NAMES[sector.id] || sector.name,
    projects: Array.isArray(sector.projects) ? sector.projects.map(localizeProject) : sector.projects,
  }));
}
